### ISSUE TITLE
Similarities to Korolev

### ISSUE THREAD

**Issue by andersstorhaug** [pragmatrix/backpanel#12]
This project shares some similarities to [Korolev](https://github.com/fomkin/korolev) for Scala/JVM, with main differences as I see (correct me if needed):
* DOM diffing: backpanel does front-end DOM patching with picodom, while Korolev produces a DOM diff in the back-end
* Document DSL: backpanel uses a Flat UI-based document DSL, while Korolev uses a DSL that's closer to raw HTML

I'm really interested in this concept and am happy to see an attempt in F# -- thought I'd point this project out as maybe it can be of some use to you.

**Comment by pragmatrix** [comment]
Hey @andersstorhaug, thank you for pointing me to Korolev. I did not know about it and will definitely take a look.

Regarding backpanel, I don't know yet where this project goes. That largely depends on the requirements that will come up. 

In the long term, I guess that the DOM diff should be done in the backend, but I'll wait for that until a performance problem appears. For now, the DOM diff is done to preserve transient UI states only (animations, cursor positions, etc.).

And the DSL is a work in progress. I see it more like a DSL that describes Bootstrap pages. I find HTML too low-level for my uses, but also recognize that it will limit the utility of the DSL.
